### ISSUE TITLE
compose run error

### ISSUE THREAD

**Issue by MarcinKosinski** [big-data-europe/docker-hive#1]
Have you ever encountered such an error during docker-compose up for this container?

````{R}
mkosinski@mkosinski-E540:~/docker-hive$  docker network create hadoop
7a8627aba8bc0e37d2e438e026db3107fc7620e81d72ef40e81b73fcbc9881e8
mkosinski@mkosinski-E540:~/docker-hive$  docker-compose up
Pulling namenode (bde2020/hadoop-namenode:1.0.0)...
1.0.0: Pulling from bde2020/hadoop-namenode
6474ebfb7a3e: Already exists
a3ed95caeb02: Already exists
cc291fac9843: Already exists
a6d9a463c720: Already exists
10c553e17298: Already exists
23026f469b0b: Already exists
e73a3f9476ba: Already exists
8d344294cd55: Already exists
40028b4987ae: Already exists
cc226e6c8064: Already exists
bacb0e395a28: Already exists
10d56ed80b63: Already exists
43bc867263cb: Already exists
94259324302c: Already exists
2fa4c7548814: Already exists
Digest: sha256:c07c915f7e90f8ae312083afed35e79f74c40126f15cc516d97b4d86be62a917
Status: Downloaded newer image for bde2020/hadoop-namenode:1.0.0
Pulling datanode1 (bde2020/hadoop-datanode:1.0.0)...
1.0.0: Pulling from bde2020/hadoop-datanode
6474ebfb7a3e: Already exists
a3ed95caeb02: Already exists
6bdc69916002: Already exists
260a74adaeb3: Already exists
e845ba0c0170: Already exists
8767d43e9712: Already exists
8c55e2d06954: Already exists
342f6ce559e7: Already exists
edcc976eae6d: Already exists
14921796925c: Already exists
d16284cecb54: Already exists
a577c290d944: Already exists
4cb3543af39b: Already exists
c2c5bc740b61: Already exists
1a800ce111be: Already exists
Digest: sha256:e35ae0bf7a8de059d1082d62fefa3e5f8e03984a9d83134fa52d1a4bf4015ced
Status: Downloaded newer image for bde2020/hadoop-datanode:1.0.0
Pulling hive (bde2020/hive:latest)...
latest: Pulling from bde2020/hive
6474ebfb7a3e: Already exists
a3ed95caeb02: Already exists
2dd6e1627e0d: Already exists
fd7a2d48248b: Already exists
d4ced813e691: Already exists
ceba6e3f04f7: Already exists
4483d2217c20: Already exists
34b26e66e536: Already exists
ee65fe633f9d: Already exists
d511ed7a5353: Already exists
a0a4a483f533: Already exists
f14e7f36bf10: Already exists
a88a8aecfb20: Pull complete
36aed70eec60: Pull complete
6be34e49cb4f: Pull complete
d9fde58d5ed4: Pull complete
40ba71786be4: Pull complete
5b3ac5ace6fc: Pull complete
f0653bb3244f: Pull complete
275ccce42392: Pull complete
7e259572ae18: Pull complete
ba7d9d3179ad: Pull complete
Digest: sha256:a967a78b2d88aaee1de82a55552f24512d99f60e094a52fef6448fe7f856d404
Status: Downloaded newer image for bde2020/hive:latest
Starting 58900ede7571_namenode
Starting datanode1
Recreating a08ec6781658_a08ec6781658_hive
Starting datanode3
Starting datanode2

ERROR: for hive  No such image: sha256:f9dac89ff5c716eef59a61168cf6a0ca2f726cb3f625e1e41175c4c317f81160
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1

````

**Comment by gmouchakis** [comment]
I have never encountered this error and it seems like it is a Docker related error. Maybe the bde2020/hive image could not be fould. Can you run
`docker rmi bde2020/hive`
`docker pull bde2020/hive` 
and try again?
