### ISSUE TITLE
WARN jdbc.HiveConnection: Failed to connect to localhost:10000

### ISSUE THREAD

**Issue by mat-ale** [big-data-europe/docker-hive#24]
Hi,

this is my configuration:

```yml
hive-server:
    container_name:           hive-server
    image:                    bde2020/hive:2.3.2-postgresql-metastore
    env_file:
          - ./hive_build/hadoop-hive.env
    environment:
        HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
        SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
        - "10000:10000"
    
hive-metastore:
    container_name:           hive-metastore
    image:                    bde2020/hive:2.3.2-postgresql-metastore
    env_file:
        - ./hive_build/hadoop-hive.env
    command:                  /opt/hive/bin/hive --service metastore
    environment:
        SERVICE_PRECONDITION: "hadoop-namenode:50070 hadoop-datanode1:50075 hive-metastore-postgresql:5432"
    ports:
        - "9083:9083"

hive-metastore-postgresql:
    container_name:           hive-metastore-postgresql
    image:                    bde2020/hive-metastore-postgresql:2.3.0
    ports:
        - "5433:5432"
```

and HIVE should be connected to 2 more HDFS containers (`hadoop-namenode`, `hadoop-datanode1`) that I have built and that are working just great on the right ports.

When I run:

```sh
 docker-compose exec hive-server bash
 /opt/hive/bin/beeline -u jdbc:hive2://localhost:10000
```
I get:

```sh
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/hadoop-2.7.4/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Connecting to jdbc:hive2://localhost:10000
19/04/30 12:21:53 [main]: WARN jdbc.HiveConnection: Failed to connect to localhost:10000
Could not open connection to the HS2 server. Please check the server URI and if the URI is correct, then ask the administrator to check the server status.
Error: Could not open client transport with JDBC Uri: jdbc:hive2://localhost:10000: java.net.ConnectException: Connection refused (Connection refused) (state=08S01,code=0)
Beeline version 2.3.2 by Apache Hive
beeline>
```

From `docker-compose` logs I don't see specific errors so the containers seem to work fine.

Any help on this please?
Thanks

**Comment by marcuslind90** [comment]
I'm experiencing similar issues, the README file is not explicit enough.

**Comment by ntallapa12** [comment]
I am trying to connect from my local machine
beeline> !connect jdbc:hive2://hive-server:10000

I get unknownhostexception, please let us know on how to make beeline or jdbc connection

**Comment by ntallapa12** [comment]
networks:
  common-network:
    driver: overlay

adding this in docker-compose resolved the issue for me

**Comment by muzammil-irshad** [comment]
@mat-ale did you resolve your issue?

**Comment by purbanow** [comment]
I have same problem

**Comment by dhirendra31pandit** [comment]
I too have the same issue and not be able to fix it.

**Comment by jessequinn** [comment]
any resolution?

**Comment by dhirendra31pandit** [comment]
I have solved it by putting the ip address instead of localhost. As i had vm machine and your local desktop and vm localhost represent two machines. I hope this will solve your issues.

**Comment by jessequinn** [comment]
the following should resolve the issue: `beeline -u jdbc:hive2://` literally. do not include any host or port and let beeline figure it out. This seems to work well (embedded mode); however, remote mode, even with configuring with `nosasl` does not appear to work.

**Comment by jessequinn** [comment]
OK now it is resolved: 

The following needs to be done:

[startup.sh]
```
#!/bin/bash

hadoop fs -mkdir       /tmp
hadoop fs -mkdir -p    /user/hive/warehouse
hadoop fs -chmod g+w   /tmp
hadoop fs -chmod g+w   /user/hive/warehouse

cd $HIVE_HOME/bin
./hive --service hiveserver2 --hiveconf hive.server2.thrift.port=10000 --hiveconf hive.root.logger=INFO,console --hiveconf hive.server2.enable.doAs=false
```

you probably do not need ` --hiveconf hive.server2.thrift.port=10000` as i have also added to the `hadoop-hive.env`, but it doesnt hurt.

`--hiveconf hive.root.logger=INFO,console` gives me more details about problems; this is how i resolved this specific issue.

add to `hadoop-hive.env` and `hadoop.env`
```
CORE_CONF_hadoop_proxyuser_hive_hosts=*
```

and to `hadoop-hive.env`
```
HIVE_SITE_CONF_hive_server2_thrift_bind_host=0.0.0.0
HIVE_SITE_CONF_hive_server2_thrift_port=10000
HIVE_SITE_CONF_hive_metastore_event_db_notification_api_auth=false
```

**Comment by rusonding** [comment]
Logging initialized using configuration in file:/opt/hive/conf/hive-log4j2.properties Async: true
Exception in thread "main" java.lang.IllegalArgumentException: java.net.UnknownHostException: namenode
        at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:378)
        at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:320)
        at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:678)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
        at org.apache

**Comment by kshru9** [comment]
> OK now it is resolved:
> 
> The following needs to be done:
> 
> [startup.sh]
> 
> ```
> #!/bin/bash
> 
> hadoop fs -mkdir       /tmp
> hadoop fs -mkdir -p    /user/hive/warehouse
> hadoop fs -chmod g+w   /tmp
> hadoop fs -chmod g+w   /user/hive/warehouse
> 
> cd $HIVE_HOME/bin
> ./hive --service hiveserver2 --hiveconf hive.server2.thrift.port=10000 --hiveconf hive.root.logger=INFO,console --hiveconf hive.server2.enable.doAs=false
> ```

Are above commands to be executed in hiveserver cli ?

**Comment by kshru9** [comment]
> OK now it is resolved:
> 
> The following needs to be done:
> 
> [startup.sh]
> 
> ```
> #!/bin/bash
> 
> hadoop fs -mkdir       /tmp
> hadoop fs -mkdir -p    /user/hive/warehouse
> hadoop fs -chmod g+w   /tmp
> hadoop fs -chmod g+w   /user/hive/warehouse
> 
> cd $HIVE_HOME/bin
> ./hive --service hiveserver2 --hiveconf hive.server2.thrift.port=10000 --hiveconf hive.root.logger=INFO,console --hiveconf hive.server2.enable.doAs=false
> ```

Hi @jessequinn 
I tried above solution on my hiveserver docker image. It shows me following error. Can you please help with the next steps? I tried searching for the workaround. But wasnt able to find any working solution. Thanks 

![image](https://user-images.githubusercontent.com/45987734/126026799-24579855-473c-4354-bd81-3b79db9d244b.png)

**Comment by gkjax88** [comment]
这个就是去找一下防火墙，把它关闭了，或者，就是那个代理权没有设置为相应的用户了。
