### ISSUE TITLE
Not able to start hive metastore postgresql container

### ISSUE THREAD

**Issue by santjosh** [big-data-europe/docker-hive#52]
I am getting the below error while using Mac M1 (apple chip). My docker desktop is up and running fine.
All other container start, except this.

hive-metastore-postgresql: forward host lookup failed: Unknown host
docker-hive-master-hive-metastore-1             | [11/100] check for hive-metastore-postgresql:5432...
docker-hive-master-hive-metastore-1             | [11/100] hive-metastore-postgresql:5432 is not available yet
docker-hive-master-hive-metastore-1             | [11/100] try in 5s once again ...

**Comment by rea1shane** [comment]
same error, how to fix it?

```
docker-hive-hive-metastore-postgresql-1  | runtime: failed to create new OS thread (have 2 already; errno=22)
docker-hive-hive-metastore-postgresql-1  | fatal error: newosproc
docker-hive-hive-metastore-postgresql-1  |
docker-hive-hive-metastore-postgresql-1  | runtime stack:
docker-hive-hive-metastore-postgresql-1  | runtime.throw(0x524da0, 0x9)
docker-hive-hive-metastore-postgresql-1  | 	/usr/local/go/src/runtime/panic.go:527 +0x90
docker-hive-hive-metastore-postgresql-1  | runtime.newosproc(0xc820028000, 0xc820037fc0)
docker-hive-hive-metastore-postgresql-1  | 	/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
docker-hive-hive-metastore-postgresql-1  | runtime.newm(0x555ce8, 0x0)
docker-hive-hive-metastore-postgresql-1  | 	/usr/local/go/src/runtime/proc1.go:1105 +0x130
docker-hive-hive-metastore-postgresql-1  | runtime.main.func1()
docker-hive-hive-metastore-postgresql-1  | 	/usr/local/go/src/runtime/proc.go:48 +0x2c
docker-hive-hive-metastore-postgresql-1  | runtime.systemstack(0x5c4300)
docker-hive-hive-metastore-postgresql-1  | 	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
docker-hive-hive-metastore-postgresql-1  | runtime.mstart()
docker-hive-hive-metastore-postgresql-1  | 	/usr/local/go/src/runtime/proc1.go:674
docker-hive-hive-metastore-postgresql-1  |
docker-hive-hive-metastore-postgresql-1  | goroutine 1 [running]:
docker-hive-hive-metastore-postgresql-1  | runtime.systemstack_switch()
docker-hive-hive-metastore-postgresql-1  | 	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820022770 sp=0xc820022768
docker-hive-hive-metastore-postgresql-1  | runtime.main()
docker-hive-hive-metastore-postgresql-1  | 	/usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc8200227c0 sp=0xc820022770
docker-hive-hive-metastore-postgresql-1  | runtime.goexit()
docker-hive-hive-metastore-postgresql-1  | 	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200227c8 sp=0xc8200227c0
docker-hive-hive-metastore-postgresql-1 exited with code 2
```

**Comment by Kenchir** [comment]
Go the same error on M1? Did you get a way around?

**Comment by rea1shane** [comment]
Solution: https://github.com/big-data-europe/docker-hive-metastore-postgresql/pull/6
